# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1314bf2f503c4ce27419a59c6dd0f007"
name = "custom-app"
handle = "custom-app-682"
application_url = "https://cookbook-uniprotkb-deck-springer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mobilyco.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://cookbook-uniprotkb-deck-springer.trycloudflare.com/auth/callback",
  "https://cookbook-uniprotkb-deck-springer.trycloudflare.com/auth/shopify/callback",
  "https://cookbook-uniprotkb-deck-springer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
